---
settings:
  name: ONTAP tools for VMware vSphere 10.1
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: it-it,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: Tool ONTAP per documenti VMware vSphere 10,1
    url: "/index.html"
  - title: Note di rilascio
    url: "/release-notes.html"
  - section: concepts
  - section: deploy
  - section: configure
  - section: protect
  - section: manage
  - section: upgrade
  - section: migrate
  - section: automation
  - title: Note legali
    url: "/legal-notices.html"
