---
permalink: migrate/migrate-to-latest-ontaptools.html 
sidebar: sidebar 
keywords: migrate 
summary: Durante la migrazione dei dati di storage, i backend di storage vengono inseriti manualmente utilizzando le API REST. Durante la migrazione dei dati dei provider VASA, i dati vengono esportati dal database Derby esistente e importati nel database MongoDB. 
---
= Eseguire la migrazione alla versione più recente dei tool ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Durante la migrazione dei dati di storage, i backend di storage vengono inseriti manualmente utilizzando le API REST. Durante la migrazione dei dati dei provider VASA, i dati vengono esportati dal database Derby esistente e importati nel database MongoDB.


NOTE: Si consiglia di eseguire la migrazione dei tool ONTAP per il setup di VMware vSphere 9.xx solo se il setup utilizza solo la funzione del provider VASA. Se disponi di datastore NVMe e di replica vVol, non è consigliato migrare ai tool ONTAP per VMware vSphere 10,1.

*A proposito di questa attività*

La migrazione è supportata dai tool ONTAP per le release VMware vSphere 9.10D2, 9.11D4, 9,12 e 9,13 alla release 10,1.


NOTE: Come utente esistente, è necessario eseguire il backup OVA dalla versione corrente prima di eseguire l'aggiornamento alle versioni delle patch.



== Passaggi comuni di migrazione

. Distribuzione di OVA per strumenti ONTAP per VMware vSphere 10,1.
. Aggiungere l'istanza di vCenter Server che si desidera migrare agli strumenti ONTAP per VMware vSphere 10,1. Vedere link:../configure/add-vcenter.html["Aggiungere e gestire le istanze di vCenter Server"]
. Back-end dello storage integrato a livello locale dai tool ONTAP per le API vCenter del plug-in VMware vSphere. Aggiungere storage come storage per la migrazione a livello locale.
. I datastore NFS e VMFS migrati dai tool ONTAP per VMware vSphere 9.xx sono visibili nei tool ONTAP per VMware vSphere 10,1 solo dopo l'attivazione del processo di rilevamento del datastore, che potrebbe richiedere fino a 30 minuti per l'attivazione. Verificare se gli archivi dati sono visibili nella pagina Panoramica della pagina dell'interfaccia utente degli strumenti di ONTAP per VMware vSphere Plugin.




== Fasi di migrazione SRA

*Prima di iniziare*

Prima di eseguire la migrazione, assicurarsi che uno dei siti sia in uno stato protetto e l'altro sia in uno stato di recupero.


NOTE: Non eseguire la migrazione se il failover è stato appena completato e la funzione di protezione è in sospeso. Completare la protezione e quindi eseguire la migrazione. Lo stesso vale per la verifica del piano di ripristino. Una volta completato il test del piano di ripristino, ripulire il ripristino di prova e avviare la migrazione.

. Per eliminare gli strumenti ONTAP per VMware vSphere 9.xx release dell'adattatore SRA nell'interfaccia utente SRM, attenersi alla seguente procedura:
+
.. Andare alla pagina di gestione della configurazione SRM
.. Consultare la sezione Storage Replication Adapter
.. Fare clic sul menu Kebab, quindi su *Reimposta configurazione*
.. Fare clic sul menu Kebab e selezionare *Elimina*
+
Eseguire queste operazioni sui siti di protezione e ripristino.



. Installare i tool ONTAP per l'adattatore SRA VMware vSphere 10,1 sui siti di protezione e ripristino seguendo i passaggi descritti in link:../protect/configure-on-srm-appliance.html["Configurare SRA sull'appliance SRM"]
. Nella pagina dell'interfaccia utente SRM, eseguire le operazioni *Discover Arrays* e *Discover Devices* e verificare che i dispositivi siano visualizzati come prima della migrazione.




== Fasi di migrazione del provider VASA

. Abilitare la PORTA Derby 1527 sugli strumenti ONTAP esistenti per VMware vSphere. Per attivare la porta, accedere alla CLI con l'utente root ed eseguire il seguente comando:
+
[listing]
----
iptables -I INPUT 1 -p tcp --dport 1527 -j ACCEPT
----
. Distribuzione di OVA per strumenti ONTAP per VMware vSphere 10,1.
. Aggiungere l'istanza di vCenter Server che si desidera migrare agli strumenti ONTAP per VMware vSphere 10,1. Vedere link:../configure/add-vcenter.html["Aggiungere un'istanza di vCenter Server"].
. Back-end dello storage integrato locale dalle API vCenter del plug-in remoto. Aggiungi storage come ambito locale per la migrazione.
. Eseguire la seguente chiamata API per la migrazione:
+
[]
====
*Metodo HTTP ed endpoint*

Questa chiamata API REST utilizza il metodo e l'endpoint seguenti.

|===


| *Metodo HTTP* | *Percorso* 


| POST | /api/v1 
|===
*Tipo di lavorazione*

Asincrono

*Esempio Curl*

/api/v1/vcenter/{vcguid}/migration-jobs

*Esempio di input JSON* corpo di richiesta per la migrazione da 9,12 e 9,13:

{ "otv_ip": "10.12.13.45", "vasa_provider_credits": { "username": "vasauser", "password": "*******" } "database_password": "*******" }

Corpo della richiesta per un'altra migrazione delle release:

{ "otv_ip": "10.12.13.45", "vasa_provider_credits": { "username": "vasauser", "password": "*******" }

*Esempio di output JSON*

Viene restituito un oggetto lavoro. È necessario salvare l'identificatore del lavoro per utilizzarlo nel passo successivo.

{ "id": 123, "migration_id": "d50073ce-35b4-4c51-9d2e-4ce66f802c35", "status": "running" }

====
. Utilizzare il seguente URI per controllare lo stato:
+
[listing]
----
https://xx.xx.xx.xxx:8443/virtualization/api/jobmanager/v2/jobs/<JobID>?includeSubJobsAndTasks=true
----
+
Una volta completato il processo, convalidare il rapporto di migrazione. È possibile visualizzare il rapporto dalla risposta al lavoro come parte di JobData.

. Aggiungi i tool ONTAP per lo storage provider di VMware vSphere a vCenter Server e link:../configure/registration-process.html["Registrare il provider VASA su vCenter Server"].
. Stop ONTAP tools for VMware vSphere storage provider 9,10/9,11/9,12/9,13 VASA Provider service dalla console di manutenzione.
+
Non eliminare il provider VASA.

+
Una volta arrestato il vecchio provider VASA, vCenter Server esegue il failover sui tool ONTAP per VMware vSphere. Tutti i datastore e le macchine virtuali sono accessibili e vengono serviti dai tool ONTAP per VMware vSphere.

. Eseguire la migrazione delle patch utilizzando la seguente API:
+
[]
====
*Metodo HTTP ed endpoint*

Questa chiamata API REST utilizza il metodo e l'endpoint seguenti.

|===


| *Metodo HTTP* | *Percorso* 


| PATCH | /api/v1 
|===
*Tipo di lavorazione*

Asincrono

*Esempio Curl*

PATCH "/api/v1/vcenters/56d373bd-4163-44f9-a872-9adabb008ca9/Migration-jobs/84dr73bd-9173-65r7-w345-8ufdb87d43

*Esempio di input JSON*

{ "id": 123, "migration_id": "d50073ce-35b4-4c51-9d2e-4ce66f802c35", "status": "running" }

*Esempio di output JSON*

Viene restituito un oggetto lavoro. È necessario salvare l'identificatore del lavoro per utilizzarlo nel passo successivo.

{ "id": 123, "migration_id": "d50073ce-35b4-4c51-9d2e-4ce66f802c35", "status": "running" }

Il corpo della richiesta è vuoto per l'operazione patch.


NOTE: uuid è l'uuid di migrazione restituito nella risposta dell'API post-migrazione.

Una volta completata con successo l'API di migrazione delle patch, tutte le VM saranno conformi alla policy di storage.

====
. L'API di eliminazione per la migrazione è:
+
[]
====
|===


| *Metodo HTTP* | *Percorso* 


| ELIMINARE | /api/v1 
|===
*Tipo di lavorazione*

Asincrono

*Esempio Curl*

/api/v1/vcenter/{vcguid}/migration-jobs/{migration_id}

Questa API elimina la migrazione tramite ID migrazione ed elimina la migrazione su vCenter Server specificato.

====


Dopo aver eseguito correttamente la migrazione e aver registrato gli strumenti ONTAP 10,1 in vCenter Server, procedere come segue:

* Aggiornare il certificato su tutti gli host.
* Attendere qualche istante prima di eseguire le operazioni di DataStore (DS) e Virtual Machine (VM). Il tempo di attesa dipende dal numero di host, DS e VM presenti nell'installazione. Quando non si attende, le operazioni potrebbero non riuscire in modo intermittente.

