---
permalink: protect/configure-storage-replication-adapter-for-san-environment.html 
sidebar: sidebar 
keywords:  
summary: 'È necessario configurare i sistemi di archiviazione prima di eseguire Storage Replication Adapter \(SRA\) per Site Recovery Manager \(SRM\).' 
---
= Configurare SRA per gli ambienti SAN e NAS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario configurare i sistemi di archiviazione prima di eseguire Storage Replication Adapter (SRA) per Site Recovery Manager (SRM).



== Configurare SRA per gli ambienti SAN

*Cosa ti serve*

Nel sito protetto e nel sito di ripristino devono essere installati i seguenti programmi:

* SRM
+
La documentazione sull'installazione di SRM è disponibile sul sito VMware.

+
https://docs.vmware.com/en/Site-Recovery-Manager/index.html["Documentazione di VMware Site Recovery Manager"]

* SRA
+
L'adattatore è installato su SRM.



*Fasi*

. Verificare che gli host ESXi primari siano connessi alle LUN nel sistema di storage primario sul sito protetto.
. Verificare che i LUN siano in igroup con l' `ostype`opzione impostata su _VMware_ sul sistema di storage primario.
. Verificare che gli host ESXi nel sito di recovery dispongano di una connettività iSCSI appropriata alla Storage Virtual Machine (SVM). Gli host ESXi del sito secondario devono avere accesso allo storage del sito secondario e gli host ESXi del sito primario devono avere accesso allo storage del sito primario.
+
A tale scopo, verificare che gli host ESXi abbiano LUN locali connessi alla SVM o tramite il `iscsi show initiators` comando sulle SVM. Controllare l'accesso LUN per i LUN mappati nell'host ESXi per verificare la connettività iSCSI.





== Configurare SRA per gli ambienti NAS

*Cosa ti serve*

Nel sito protetto e nel sito di ripristino devono essere installati i seguenti programmi:

* SRM
+
La documentazione sull'installazione di SRM è disponibile sul sito VMware.

+
https://docs.vmware.com/en/Site-Recovery-Manager/index.html["Documentazione di VMware Site Recovery Manager"]

* SRA
+
L'adattatore viene installato su SRM e sul server SRA.



*Fasi*

. Verificare che gli archivi dati del sito protetto contengano macchine virtuali registrate con vCenter Server.
. Verificare che gli host ESXi nel sito protetto abbiano montato i volumi di esportazione NFS dalla macchina virtuale di storage (SVM).
. Verificare che gli indirizzi validi come l'indirizzo IP, il nome host o l'FQDN su cui sono presenti le esportazioni NFS siano specificati nel campo *NFS Addresses* (indirizzi NFS) quando si utilizza la procedura guidata Array Manager per aggiungere array a SRM.
. Utilizzare il `ping` comando su ciascun host ESXi nel sito di ripristino per verificare che l'host disponga di una porta VMkernel in grado di accedere agli indirizzi IP utilizzati per le esportazioni NFS dalla SVM.

