---
sidebar: sidebar 
permalink: automation/get-started-with-the-rest-api.html 
keywords: REST API 
summary: 'L"accesso all"API offre una prospettiva prima di iniziare a utilizzarla con i processi di workflow più complessi in un setup live.' 
---
= Inizia con L'API REST
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi iniziare rapidamente a utilizzare i tool ONTAP per le API REST di VMware vSphere. L'accesso all'API offre una prospettiva prima di iniziare a utilizzarla con i processi di workflow più complessi in un setup live.



== Ciao mondo

Puoi eseguire un semplice comando sul tuo sistema per iniziare a utilizzare i tool di ONTAP per l'API REST di VMware vSphere e verificarne la disponibilità.

.Prima di iniziare
* Assicurarsi che l'utility Curl sia disponibile sul sistema.
* Indirizzo IP o nome host degli strumenti ONTAP per il server VMware vSphere
* Nome utente e password per un account con autorizzazione ad accedere agli strumenti ONTAP per l'API REST VMware vSphere.



NOTE: Se le credenziali includono caratteri speciali, è necessario formattarle in modo accettabile per Curl in base alla shell in uso. Ad esempio, è possibile inserire una barra rovesciata prima di ogni carattere speciale o racchiudere l'intera stringa tra virgolette `username:password` singole.

.Fase
Nell'interfaccia della riga di comando, eseguire quanto segue per recuperare le informazioni del plug-in:

`curl -X GET -u username:password -k "\https://<ip_address>/api/hosts?fields=IncludePluginInfo"`

Esempio:

`curl -X GET -u admin:password -k "'\https://10.225.87.97/api/hosts?fields=IncludePluginInfo"`
