---
permalink: configure/create-vvols-datastore.html 
sidebar: sidebar 
keywords:  
summary: Puoi creare un datastore vVol con nuovi volumi o con volumi esistenti. Puoi anche creare un datastore vVol con la combinazione di volumi esistenti e nuovi volumi. 
---
= Creare un datastore
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando si crea un datastore a livello di cluster host, il datastore viene creato e montato su tutti gli host della destinazione e l'azione viene attivata solo se l'utente corrente dispone dei privilegi necessari per l'esecuzione.

La procedura guidata di creazione dell'archivio dati supporta la creazione di datastore NFS, VMFS e vVols.



== Creare un datastore vVol

Puoi creare un datastore vVol con nuovi volumi o volumi esistenti. Non è possibile creare un datastore vVol con un mix di volumi esistenti e nuovi.


NOTE: Controllare che gli aggregati root non siano mappati alla SVM.

.Prima di iniziare
Assicurarsi che il provider VASA sia registrato con il vCenter selezionato.

.Fasi
. Accedere al client vSphere utilizzando `\https://vcenterip/ui`
. Fare clic con il pulsante destro del mouse su un sistema host o su un cluster host o su un data center, quindi selezionare *NetApp ONTAP Tools* > *Create Datastore*.
. Nel riquadro *tipo*, selezionare vVol in *tipo datastore*.
. Nel riquadro *Nome e protocollo*, fornire le informazioni *Nome archivio dati* e *protocollo*.
. Nel riquadro *Storage*, selezionare *Platform* e *Storage VM*. Nella sezione *Opzioni avanzate*, selezionare criterio di esportazione personalizzato (per il protocollo NFS) o nome gruppo iniziatore personalizzato (per il protocollo iSCSI), a seconda dei casi.
+
** Le opzioni relative alla piattaforma e all'asimmetria consentono di filtrare le opzioni a discesa SVM. Devi selezionare la SVM per creare o utilizzare i volumi per la creazione del datastore.
** Il pulsante di commutazione *asimmetrico* è visibile solo se iSCSI è stato selezionato nella fase precedente e prestazioni o capacità è selezionato nell'elenco a discesa della piattaforma.
** Selezionare il pulsante di commutazione *asimmetrico* per la piattaforma AFF e disattivarlo per la piattaforma ASA.


. Nel riquadro *attributi archiviazione* è possibile creare nuovi volumi o utilizzare i volumi esistenti. Durante la creazione di un nuovo volume, puoi abilitare la QoS nel datastore.
. Controllare la selezione nel riquadro *Riepilogo* e fare clic su *fine*. Il datastore vVols viene creato e montato su tutti gli host.




== Creare un datastore NFS

Un datastore NFS (Network file System) di VMware utilizza il protocollo NFS per connettere gli host ESXi a un dispositivo di storage condiviso in una rete. I datastore NFS sono comunemente utilizzati negli ambienti VMware vSphere e offrono diversi vantaggi, come semplicità e flessibilità.

.Fasi
. Accedere al client vSphere utilizzando `\https://vcenterip/ui`
. Fare clic con il pulsante destro del mouse su un sistema host o un cluster host o un data center, quindi selezionare *NetApp ONTAP Tools* > *Create Datastore*.
. Nel riquadro *tipo*, selezionare NFS in *tipo datastore*.
. Nel riquadro *Nome e protocollo*, immettere il nome del datastore, le dimensioni e le informazioni sul protocollo. Nelle opzioni avanzate, selezionare *Datastore cluster* e *autenticazione Kerberos*.
+

NOTE: L'autenticazione Kerberos è disponibile solo quando è selezionato il protocollo NFS 4,1.

. Nel riquadro *Storage*, selezionare *Platform* e *Storage VM*. È possibile selezionare *criterio di esportazione personalizzato* nella sezione *opzione avanzata*.
+
** Il pulsante di commutazione *asimmetrico* è visibile solo se nel menu a discesa della piattaforma sono selezionate le prestazioni o la capacità.
** *Any* (qualsiasi opzione) nel menu a discesa delle piattaforme consente di visualizzare tutte le SVM che fanno parte di vCenter, indipendentemente dalla piattaforma o dal flag asimmetrico.


. Nel riquadro *attributi archiviazione*, selezionare l'aggregato per la creazione del volume. Nelle opzioni avanzate scegliere *Riserva spazio* e *attiva QoS* come richiesto.
. Rivedere le selezioni nel riquadro *Riepilogo* e fare clic su *fine*.


Il datastore NFS viene creato e montato su tutti gli host.



== Creare un datastore VMFS

Virtual Machine file System (VMFS) è un file system in cluster appositamente progettato per l'archiviazione dei file delle macchine virtuali negli ambienti VMware vSphere. Consente a più host ESXi di accedere contemporaneamente ai file della stessa macchina virtuale, abilitando funzionalità come vMotion e High Availability.

.Fasi
. Accedere al client vSphere utilizzando `\https://vcenterip/ui`
. Fare clic con il pulsante destro del mouse su un sistema host o un cluster host o un datastore, quindi selezionare *NetApp ONTAP Tools* > *Create Datastore*.
. Nel riquadro *tipo*, selezionare VMFS in *tipo datastore*.
. Nel riquadro *Nome e protocollo*, immettere il nome del datastore, le dimensioni e le informazioni sul protocollo. Nella sezione *Opzioni avanzate* del riquadro, selezionare il cluster di datastore a cui si desidera aggiungere il datastore.
. Selezionare piattaforma e VM di archiviazione nel riquadro archiviazione. Selezionare il pulsante di commutazione asimmetrico. Specificare il nome del gruppo *personalizzato iniziatore* nella sezione *Opzioni avanzate* del riquadro (facoltativo). È possibile scegliere un igroup esistente per l'archivio dati o creare un nuovo igroup con un nome personalizzato.
+
Se si sceglie l'opzione *any* nel menu a discesa delle piattaforme, è possibile visualizzare tutte le SVM che fanno parte di vCenter, indipendentemente dalla piattaforma o dal flag asimmetrico.

. Nel riquadro degli attributi di archiviazione, selezionare *aggregate* dal menu a discesa. Selezionare le opzioni *riserva di spazio*, *Usa volume esistente* e *attiva QoS* come richiesto nella sezione *Opzioni avanzate* e fornire i dettagli come richiesto.
. Rivedere i dettagli del datastore nel riquadro *Riepilogo* e fare clic su *fine*. Il datastore VMFS viene creato e montato su tutti gli host.

