---
permalink: release-notes/release-notes.html 
sidebar: sidebar 
keywords: release notes, ontap tools for VMware vSphere 
summary: Fornisce importanti informazioni su questa release di strumenti ONTAP per VMware vSphere, tra cui nuove funzionalità e miglioramenti, problemi risolti, problemi noti, precauzioni e limitazioni. 
---
= Note di rilascio
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Scopri le nuove e migliorate funzioni disponibili nei tool ONTAP per VMware vSphere 10,1.

Per un elenco completo delle nuove funzioni e dei miglioramenti, vedere xref:whats-new-otv-101.adoc[Novità dei tool ONTAP per VMware vSphere 10,1].

Per ulteriori informazioni sull'opportunità di eseguire la migrazione dagli strumenti ONTAP per VMware vSphere 9 agli strumenti ONTAP 10,1 , consultare xref:otv-9-otv10-feature-comparison.adoc[Confronto delle funzioni di OTV 9 e OTV 10]. La migrazione è supportata dai tool ONTAP per le release VMware vSphere 9.10D2, 9.11D4, 9,12 e 9,13 agli strumenti ONTAP 10,1.

Per informazioni dettagliate sui problemi e le limitazioni noti degli strumenti ONTAP per VMware vSphere 10,1, fare riferimento alla https://library.netapp.com/ecm/ecm_get_file/ECMLP3319071["Note sulla versione dei tool ONTAP per VMware vSphere 10,1"^] . Per accedere alle Note di rilascio, è necessario accedere con l'account NetApp o creare un account.
