---
permalink: manage/delete-vvols.html 
sidebar: sidebar 
keywords: vVols datastore,delete vVol 
summary: 'L"azione Elimina archivio dati elimina il datastore. Nel caso del datastore NFS o VMFS, viene visualizzata una finestra di dialogo con l"elenco delle macchine virtuali che utilizzano il datastore.' 
---
= Elimina datastore
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La rimozione dello storage dall'azione del datastore è supportata su tutti i tool ONTAP per i datastore vVol VMware vSphere rilevati o gestiti in vCenter Server. Questa azione consente la rimozione di volumi dal datastore vVol.

L'opzione di rimozione è disattivata quando sono presenti vVol su un volume specifico. Oltre a rimuovere i volumi dal datastore, puoi eliminare il volume selezionato sullo storage ONTAP.

Eliminare l'attività del datastore dai tool ONTAP per VMware vSphere in vCenter Server esegue le seguenti operazioni:

* Smonta il container vVol.
* Pulisce l'igroup. Se igroup non viene utilizzato, rimuove iqn dall'igroup.
* Elimina il contenitore Vvol.
* Lascia i volumi Flex nell'array di storage.


Segui i passaggi riportati di seguito per eliminare il datastore NFS, VMFS o vVOL dagli strumenti ONTAP da vCenter Server:

.Fasi
. Accedere al client vSphere utilizzando `\https://vcenterip/ui`
. Fare clic con il pulsante destro del mouse su un sistema host, un cluster host o un datastore, quindi selezionare *NetApp ONTAP tools* > *Delete datastore*.
+

NOTE: Non è possibile eliminare gli archivi dati se ci sono macchine virtuali che utilizzano tale archivio dati. Prima di eliminare l'archivio dati, è necessario spostare le macchine virtuali in un altro datastore.

+
.. Nel caso del datastore NFS o VMFS, viene visualizzata una finestra di dialogo con l'elenco delle macchine virtuali che utilizzano il datastore.
.. Nel caso dell'archivio dati vVol, l'azione Elimina archivio dati elimina l'archivio dati solo quando non vi sono vVol associati. La finestra di dialogo Elimina datastore offre un'opzione per eliminare i volumi dal cluster ONTAP.


. Per eliminare i volumi di backup sull'archiviazione ONTAP, selezionare *Elimina volumi sul cluster ONTAP*.

